// These are actions for User.
const USER_LOGIN = "USER_LOGIN";
const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

const USER_SIGNUP = "USER_SIGNUP";
const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

const FORGOT_PASSWORD = "FORGOT_PASSWORD";
const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

const RESET_PASSWORD = "RESET_PASSWORD";
const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export {
  USER_LOGIN,
  USER_LOGIN_ERROR,
  USER_SIGNUP,
  USER_SIGNUP_ERROR,
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_ERROR,
  RESET_PASSWORD,
  RESET_PASSWORD_ERROR,
};
